FROM python:3.12-slim

WORKDIR /app

COPY requirements.flask.txt .
RUN pip install --no-cache-dir -r requirements.flask.txt

COPY ./flask_app ./flask_app
COPY ./shared ./shared
COPY start_flask.py .

CMD ["python", "start_flask.py"]