require_relative 'env_loader'

Vagrant.configure("2") do |config|
  (1..3).each do |i|
    config.vm.define "sftp#{i}" do |node|
      node.vm.box = "ubuntu/bionic64"
      node.vm.hostname = "sftp#{i}"
      node.vm.network "private_network", ip: ENV["SFTP_IP_#{i}"]
    end
  end

  # Provisioning scripts (will not run automatically)
  config.vm.provision "initial_setup", type: "shell", path: "scripts/initial_setup.sh", privileged: true, run: "never"
  config.vm.provision "create_sftp_user", type: "shell", path: "scripts/create_sftp_user.sh", privileged: true, run: "never", env: {"SFTP_USERNAME" => ENV['SFTP_USERNAME'], "SFTP_PASSWORD" => ENV['SFTP_PASSWORD']}
  config.vm.provision "generate_ssh_key", type: "shell", path: "scripts/generate_ssh_key.sh", privileged: true, run: "never", env: {"SFTP_USERNAME" => ENV['SFTP_USERNAME']}
  config.vm.provision "exchange_keys", type: "shell", path: "scripts/exchange_ssh_keys.sh", privileged: true, run: "never", env: {"SFTP_USERNAME" => ENV['SFTP_USERNAME'], "SFTP_PASSWORD" => ENV['SFTP_PASSWORD'], "SFTP_IP_1" => ENV['SFTP_IP_1'], "SFTP_IP_2" => ENV['SFTP_IP_2'], "SFTP_IP_3" => ENV['SFTP_IP_3']}
  config.vm.provision "setup_sftp", type: "shell", path: "scripts/setup_sftp_script.sh", privileged: true, run: "never", env: {"SFTP_USERNAME" => ENV['SFTP_USERNAME'], "SFTP_IP_1" => ENV['SFTP_IP_1'], "SFTP_IP_2" => ENV['SFTP_IP_2'], "SFTP_IP_3" => ENV['SFTP_IP_3']}
  config.vm.provision "disable_password_auth", type: "shell", path: "scripts/disable_password_auth.sh", privileged: true, run: "never"
  config.vm.provision "add_local_key", type: "shell", path: "scripts/add_local_key.sh", privileged: true, run: "never", env: {"SFTP_USERNAME" => ENV['SFTP_USERNAME']}
end