require_relative 'env_loader'

Vagrant.configure("2") do |config|
  (1..3).each do |i|
    config.vm.define "sftp#{i}" do |node|
      node.vm.box = "ubuntu/bionic64"
      node.vm.hostname = "sftp#{i}"
      node.vm.network "private_network", ip: "192.168.33.#{10+i}"
    end
  end

  # Provisioning scripts (will not run automatically)
  config.vm.provision "initial_setup", type: "shell", path: "initial_setup.sh", privileged: true, run: "never"
  config.vm.provision "create_sftp_user", type: "shell", path: "create_sftp_user.sh", privileged: true, run: "never", env: {"SFTP_USERNAME" => ENV['SFTP_USERNAME'], "SFTP_PASSWORD" => ENV['SFTP_PASSWORD']}
  config.vm.provision "generate_ssh_key", type: "shell", path: "generate_ssh_key.sh", privileged: true, run: "never", env: {"SFTP_USERNAME" => ENV['SFTP_USERNAME']}
  config.vm.provision "exchange_keys", type: "shell", path: "exchange_ssh_keys.sh", privileged: true, run: "never", env: {"SFTP_USERNAME" => ENV['SFTP_USERNAME'], "SFTP_PASSWORD" => ENV['SFTP_PASSWORD']}
  config.vm.provision "setup_sftp", type: "shell", path: "setup_sftp_script.sh", privileged: true, run: "never", env: {"SFTP_USERNAME" => ENV['SFTP_USERNAME']}
  config.vm.provision "disable_password_auth", type: "shell", path: "disable_password_auth.sh", privileged: true, run: "never"
end