version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile-Backend
    ports:
      - "8080:8080"
    depends_on:
      - postgres
      - redis

  frontend:
    build:
      context: .
      dockerfile: Dockerfile-Frontend
    ports:
      - "3000:3000"

  postgres:
    build:
      context: .
      dockerfile: Dockerfile-PostgreSQL
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    build:
      context: .
      dockerfile: Dockerfile-Redis
    ports:
      - "6379:6379"

volumes:
  postgres_data: