version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile-Backend
    ports:
      - "8080:8080"
    env_file:
      - .env
    environment:
      - DATABASE_URL=jdbc:postgresql://postgres:5432/${POSTGRES_DB}
      - DATABASE_USER=${POSTGRES_USER}
      - DATABASE_PASSWORD=${POSTGRES_PASSWORD}
      - REDIS_URL=redis://${REDIS_HOST}:${REDIS_PORT}
    depends_on:
      - postgres
      - redis

  frontend:
    build:
      context: ./frontend
      dockerfile: ../Dockerfile-Frontend
    ports:
      - "3000:3000"
    env_file:
      - .env

  postgres:
    build:
      context: .
      dockerfile: Dockerfile-PostgreSQL
    ports:
      - "5432:5432"
    env_file:
      - .env
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_ready -U ${POSTGRES_USER} -d ${POSTGRES_DB}" ]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: always

  redis:
    build:
      context: .
      dockerfile: Dockerfile-Redis
    ports:
      - "6379:6379"
    env_file:
      - .env

volumes:
  postgres_data: