variable "postgres_db" {}
variable "postgres_user" {}
variable "postgres_password" {}
variable "redis_port" {}
variable "mongo_database" {}
variable "redis_host" {}
variable "redis_protocol" {}
variable "default_server_cluster" {}
variable "react_app_api_base_url" {}
variable "backend_image" {}
variable "frontend_image" {}
variable "aws_region" {}
variable "aws_account_id" {}
variable "private_key" {}
variable "key_name" {}